### ISSUE TITLE
Entity search in hierarchy tab

### ISSUE THREAD

**Issue by rewin123** [rewin123/space_editor#104]
Entity search by name will be usefull when entoty count is big

**Comment by pearl2201** [comment]
Did anyone touch it? I want to help you guys a little?

**Comment by rewin123** [comment]
Haven't touched it yet, any help would be appreciated ^_^

**Comment by naomijub** [comment]
I think it should be pretty straightforward and similar to component search

**Comment by naomijub** [comment]
@pearl2201 Have you gotten anything on this? Do you need help?

**Comment by ncomendant** [comment]
I'm up for trying this one, if that's alright with everyone.

**Comment by naomijub** [comment]
> I'm up for trying this one, if that's alright with everyone.

I waiting on @pearl2201 response on this one

**Comment by ncomendant** [comment]
Sounds good!

**Comment by rewin123** [comment]
Entity search was made
