### ISSUE TITLE
Remove Clone requirement for component, which registered in editor

### ISSUE THREAD

**Issue by rewin123** [rewin123/space_editor#123]
```rust
/// register new component in editor UI and prefab systems
fn editor_registry<
    T: Component + Default + Send + 'static + GetTypeRegistration + Clone + Reflect + FromReflect,
>(
    &mut self,
) -> &mut Self;
```

Clone can be removed and clone operation can be done on pure reflect logic

**Comment by naomijub** [comment]
I think the only way to remove this is with unsafe https://stackoverflow.com/a/58255749/5425532

**Comment by rewin123** [comment]
```rust
let original: Box<dyn Reflect> = Box::new(MyStruct {
  foo: 123
});

let cloned: Box<dyn Reflect> = original.clone_value();
let value = cloned.take::<MyStruct>().unwrap(); // PANIC!
```

Reflect based cloning example from bevy docs which i want to use

**Comment by naomijub** [comment]
I updated the PR with this. However, main seems broken. Platformer test_level is not loading

**Comment by rewin123** [comment]
Hm. I tested befor tag 0.3. Will test it too today

**Comment by rewin123** [comment]
![image](https://github.com/rewin123/space_editor/assets/10954133/9c8b0e0a-b8c8-4adf-ae05-7b8b53dba8e8)
Works for me

**Comment by rewin123** [comment]
I need to add asset loading in tests:D

**Comment by naomijub** [comment]
Did you load from example folder or from bottom menu load scene?

**Comment by naomijub** [comment]
Will try to figure out the issue, can you check if the PR works? https://github.com/rewin123/space_editor/pull/126

**Comment by rewin123** [comment]
Found that clone not workingh now in pr

**Comment by naomijub** [comment]
Comparing src entity with destination entity I see that destination entity is larger than src 😕

**Comment by rewin123** [comment]
I cheated a little bit. Here's the correct code

```rust
#[derive(Reflect)]
struct MyStruct {
  foo: i32
}
let original: Box<dyn Reflect> = Box::new(MyStruct {
  foo: 123
});

let cloned: Box<dyn Reflect> = original.clone_value();
let value = <MyStruct as FromReflect>::from_reflect(&*cloned).unwrap(); // OK!
```
