### ISSUE TITLE
Failed to load GLTF

### ISSUE THREAD

**Issue by naomijub** [rewin123/space_editor#132]
I moved the PUG assets from [Kenney's](https://kenney.nl/assets) to our asset's folder and when I tried to import it, it failed to load.
https://drive.google.com/drive/folders/1UNNT0MeVX0O04RGgu8aLkKe3fwB9_t-A

**Comment by rewin123** [comment]
I added support for multiple primitives in mesh. But next wgpu is failing with weird error when pug loaded

**Comment by ncomendant** [comment]
I'm getting a `wgpu error: Validation Error`, too. I'm pretty sure it's related to the following snippet, but not sure how to resolve it:
https://github.com/rewin123/space_editor/blob/1a7c0b7357c0485842a743ddfd94d44811009b1b/crates/editor_core/src/gltf_unpack.rs#L221C31-L228

**Comment by naomijub** [comment]
Is it multimaterial?

**Comment by ncomendant** [comment]
Yes, I believe it has three. Also I just tried your pug, and yep, same error.

**Comment by rewin123** [comment]
I created "crutch" in just-dev-2, which allow to save scene children states. It allow to skip unpack process of gltf and move around "bug position". Will create PR soon for it

**Comment by naomijub** [comment]
This PR should fix it https://github.com/rewin123/space_editor/issues/183
@ncomendant can you try the branch as well? it solved my issue
