### ISSUE TITLE
Write custom debug grid crate

### ISSUE THREAD

**Issue by rewin123** [rewin123/space_editor#138]
bevy_debug_grid doesn't work well with multiple cameras, bevy_inifinite_grid still hasn't uploaded a version for bevy 0.12. 

We need to either upload a fix to bevy_debug_grid for normal support of multiple cameras, or make own library, for example, just based on Gizmos from bevy (but then we will lose the ability to choose on which specific cameras the coordinate grid should be displayed). 

At the moment I've uploaded a very simple grid rendering based on Gizmos as a temporary solution.

**Comment by naomijub** [comment]
I think infinite grid has been merged to bevy 0.12
https://github.com/ForesightMiningSoftwareCorporation/bevy_infinite_grid/pull/43

**Comment by naomijub** [comment]
I think this can be closed as won't do after @ncomendant PR has been merged
