### ISSUE TITLE
[Camera] Camera View Tab overlaps with Game view

### ISSUE THREAD

**Issue by naomijub** [rewin123/space_editor#140]
When moving Camera View Tab to the same node as Game View Tab, the cameras overlap causing the issue below:
<img width="861" alt="Captura de Tela 2023-12-29 às 7 08 58 PM" src="https://github.com/rewin123/space_editor/assets/14813660/21b49dad-a20c-4169-8bfb-0c8cdbd1e344"> 

This overlap happens with any of the two tabs selected.

Ideally, the Camera View would be hidden when in Game View, and Game View would be hidden when in Camera View.

The Camera works fine in other scenarios:
<img width="746" alt="Captura de Tela 2023-12-29 às 7 09 13 PM" src="https://github.com/rewin123/space_editor/assets/14813660/35e6be68-200f-41f6-8fb7-b79c0cf26c1b">

<img width="1089" alt="Captura de Tela 2023-12-29 às 7 08 48 PM" src="https://github.com/rewin123/space_editor/assets/14813660/49027db4-b3db-416d-93c2-1ffb019e97ef">

**Comment by rewin123** [comment]
I tried various reasonable ways over yesterday to avoid writing to the texture of the camera view, so as not to create additional data. However, all attempts failed. I'll try to upload a fix with texture writing today

**Comment by naomijub** [comment]
Sounds good

**Comment by rewin123** [comment]
I think it fixed. But it's a floating bug. @naomihub can you confirm that it's fixed for you too?

**Comment by rewin123** [comment]
Overlapping is fixed. This issue can be closed
