### ISSUE TITLE
Update egui_file to 0.14

### ISSUE THREAD

**Issue by naomijub** [rewin123/space_editor#157]
Based on merge of PR #155 we need to update [egui_file](https://github.com/Barugon/egui_file) to version 0.14+

**Comment by MickHarrigan** [comment]
I can make a PR for this soon, but the big change is that egui itself updated, so all the egui libraries will be updating to update [egui_file](https://github.com/Barugon/egui_file) as well.

**Comment by rewin123** [comment]
Ye. Some of them, like bevy_egui, have not been updated yet. I think we need to wait before all the crates are updated.
