### ISSUE TITLE
Fix separation of GLTF/GLB meshes from parent entities

### ISSUE THREAD

**Issue by MickHarrigan** [rewin123/space_editor#183]
Currently when importing GLTF files, either from the ui as a prefab or from a `.scn.ron` an entity is created for the object mesh (or collection of meshes) as well as an entity that seems to be the parent of the mesh.

In the platformer example this is seen with the columns as clicking on them allows moving the mesh via the gizmo but
1. it does not select the parent entity in the hierarchy
2. the parent is not named as the column (or whatever name it should have)
3. the parent is not shown to have any children.

I think that this issue can be solved using some of the code in #146 with the `SelectParent` component that allows any clicking on a mesh to be passed to a different entity specifically.

On the other hand, if you have a gltf that is a multitude of meshes that have a collective parent entity this solution could have other issues where each part cannot be individually selected. Maybe a separate mode or selection method may be used to solve this.

Edit: After looking more into the simpler scenes that are included it seems that the serialization process adds many layers of entities for each gltf. This is not only cluttered, but also clunky as selecting the mesh in the editor window affects a different entity than what is in the hierarchy.
For example, the parenting example scene:
![image](https://github.com/rewin123/space_editor/assets/37913967/64320baa-27a2-4419-af3d-7c14f82ee0c0)
Neither cube is in the hierarchy. But when expanded to show all entities:
![image](https://github.com/rewin123/space_editor/assets/37913967/69ca0745-9a37-4be0-9aa9-a8de0b541fda)

This is what I think the issue actually is. Especially since looking at importing gltf as-is does not have this problem the issue comes from the saving and loading of `{}.scn.ron`.

**Comment by rewin123** [comment]
Fixed it just-dev-2 branch. Will create PR soon

**Comment by MickHarrigan** [comment]
ah that does fix that part.

On the other hand while messing with this myself I found a bit of a discrepancy between importing a gltf which serializes as
```ron
"space_prefab::component::AssetMesh": (
  path: "cube.glb#Mesh0/Primitive0",
),
"space_prefab::component::AssetMaterial": (
  path: "cube.glb#Material0",
),
```
which does not have the massive amount of entities and chains.
Is this functionally different from the `parent_test.scn.ron` serialization of
```ron
"space_prefab::component::GltfPrefab": (
  path: "cube.glb",
  scene: "Scene0",
),
```

**Comment by rewin123** [comment]
Ye. Its two very different path for serialization. 

First loading sub-assets from gltf asset. Directly loading mesh/material/postion from raw gltf. It allow to change the gltf scene and save this changes.

Second path allow bevy to decide how to load gltf. But editor can not save any chainges of children of gltf scene.

**Comment by MickHarrigan** [comment]
Ok that makes sense that they have differences.

Other than that, how as a user can you make some scene and then save it in one or the other format? From what I have been able to figure out it seems that it is harder to get the second option to happen compared to just importing the gltf and saving that as the first option.

If there is a clear distinction for how each can be used that I think would be important longer term.

Additionally when serializing as the `GltfPrefab` does the hierarchy of entities need to be as deep as it is? Or is there a way to reduce the noise in the hierarchy overall?

**Comment by rewin123** [comment]
When using the GltfPrefab component, the entity hierarchy is generated by bevy. I don’t think this point is worth touching, especially since the hierarchy of entities loaded as children of the gltf scene is not currently visualized

**Comment by rewin123** [comment]
If you need to pass an event to the parent from a primitive, then I think you can somehow mark the primitives in the gltf scene so that they pass control

**Comment by MickHarrigan** [comment]
I did some looking at the bevy examples and yes, you are correct that the hierarchy comes from bevy itself on that. I do think that in the future it may be useful to have the mesh that is selected select the parent or some other entity instead of just the mesh entity but the changes in `just-dev-2` should work anyways.

**Comment by naomijub** [comment]
This is fixed right?

**Comment by rewin123** [comment]
Its fixed in just-dev-2, which I can not merge (merge conflicts solved bad).
I will try to recreate PR on this weekend

**Comment by rewin123** [comment]
Fixed
