### ISSUE TITLE
Define Design System for Editor

### ISSUE THREAD

**Issue by naomijub** [rewin123/space_editor#186]
Space Editor needs a design system and it should be correlated to Bevy Editor Prototype discussions.
- One partial reference for this is https://github.com/coreh/bevy-rfcs/blob/editor-design-system/rfcs/69-editor-design-system.md

**All suggestions and ideas are welcomed in this issue**

**Comment by naomijub** [comment]
@rewin123 Here is the [figma](https://www.figma.com/file/Bc8ct1T3ETv94CHoZidF11/Space-Editor?type=design&node-id=0%3A1&mode=design&t=LXMMAjo9QaGocotj-1) we are working on for the project

**Comment by rewin123** [comment]
Great!

**Comment by rewin123** [comment]
I'm not very friendly with figma, but I can also participate tomorrow

**Comment by naomijub** [comment]
Don't worry, we will let you know when it is ready to feedback

**Comment by naomijub** [comment]
Asour8 proposed a mockup for the bevy editor that brings some interesting elements that I want to be addressed those elements in space_editor:
- [ ] Skip a frame button in Play Mode and Edit Mode
- [ ] Virtual time multiplication slider
- [ ] Feature flag section (probably its own tab)
- [ ] Justified add component button
- [ ] Warn|Error console alerts
- [ ] Check feasibility of adding some space between the docked tabs in egui_dock


![image](https://github.com/rewin123/space_editor/assets/14813660/41b75789-6a11-4115-8aea-43328913d409)

**Comment by naomijub** [comment]
https://github.com/rewin123/space_editor/pull/189

**Comment by naomijub** [comment]
Closing for now
