### ISSUE TITLE
Cannot load editor as dependency, because icon is not loading

### ISSUE THREAD

**Issue by rewin123** [rewin123/space_editor#191]
When use space_editor as dependency, its trying to load icons from top root asset folder, not from space_editor asset folder

**Comment by naomijub** [comment]
I have a fix for this, will push in my next PR

**Comment by naomijub** [comment]
PR #201 should have fixed this. Can you doublecheck

Works on my side

**Comment by rewin123** [comment]
> PR #201 should have fixed this. Can you doublecheck
> 
> Works on my side

Will check today
