### ISSUE TITLE
Clicking on an entity in the Hierarchy does not select it in the editor so i cannot translate it .. 

### ISSUE THREAD

**Issue by ethereumdegen** [rewin123/space_editor#197]
Clicking on an entity in the Hierarchy does not select it in the editor so i cannot translate it ..

**Comment by ethereumdegen** [comment]
I added a GLTF model and it has some sub-meshes so it appears in the hierarchy as a parent entity and 4 children.  My problem is, i have absolutely no way of transforming the parent - which is what i NEED to do.   clicking on it in the hierarchy ui, nothing. trying to click in it 3d, nothing.  How the heck can i transform a gltf model? (not just its children but its root )? ??

**Comment by naomijub** [comment]
We identified that bug yesterday and we are working on it. If you want I know this commit is stable 200b41291e02f0cfcd53e1cac70429926e2f2185

I'm really sorry, @rewin123 is looking into that

**Comment by rewin123** [comment]
Fixed
