### ISSUE TITLE
It should be possible to make an entity be the child of another entity. 

### ISSUE THREAD

**Issue by ethereumdegen** [rewin123/space_editor#207]
It should be possible to make an entity be the child of another entity.  Perhaps  drag and dropping it  in the hierarchy.

**Comment by naomijub** [comment]
Good suggestion, we don't have a lot of drag and drops, but it should definitely work

**Comment by rewin123** [comment]
We can do it with right click on new parent entity

![ezgif-7-5330fed8e8](https://github.com/rewin123/space_editor/assets/10954133/eb267328-cb40-414f-b408-4082d8b38127)
