### ISSUE TITLE
It would be nice if 'add prefab' set the initial transform to a location of my choice, not (0,0,0)

### ISSUE THREAD

**Issue by ethereumdegen** [rewin123/space_editor#219]
It would be nice if 'add prefab' set the initial transform to a location of my choice, not (0,0,0)

my work flow right now has me panning all the way over to (0,0,0) and back to where i am working and it takes a long time

**Comment by naomijub** [comment]
Once we have the drag and drop from content browser, it should be easy to avoid this

**Comment by naomijub** [comment]
Something Like this would be cool as well https://bevyengine.org/examples/3D%20Rendering/3d-viewport-to-world/

- Hold ctrl sets spawn point the the grid, and cancels, when you spawn it spanws in the position where you released Ctrl
- Camera could be holding Alt.
Not sure if this helps for the Y coordinate

**Comment by rewin123** [comment]
Okey. Based on bevy_mod_raycast we can do this for entities with Transform component

**Comment by rewin123** [comment]
Fixed in #281
