### ISSUE TITLE
Double "undo"

### ISSUE THREAD

**Issue by Tymofii-Lytvynenko** [rewin123/space_editor#232]
I think first "undo" must be view? (3d/2d)
![image](https://github.com/rewin123/space_editor/assets/77191670/54f2f765-910b-4acf-9699-de50d5bcb6ce)

**Comment by rewin123** [comment]
Looks like a merge mistake

**Comment by naomijub** [comment]
This has already been fixed, which version are you using?
<img width="1020" alt="Captura de Tela 2024-03-02 às 2 39 31 PM" src="https://github.com/rewin123/space_editor/assets/14813660/7c68844d-8746-438d-859e-735d4196e695">
