### ISSUE TITLE
When descrease Camera view tab size program can crash

### ISSUE THREAD

**Issue by rewin123** [rewin123/space_editor#245]
![image](https://github.com/rewin123/space_editor/assets/10954133/1e5e748f-2b2c-4185-b0f3-df209153a201)
![image](https://github.com/rewin123/space_editor/assets/10954133/61885a45-ee1a-4555-a972-447741bc5a6d)

**Comment by naomijub** [comment]
Seems to be deeply related  https://github.com/rewin123/space_editor/issues/254

**Comment by naomijub** [comment]
We can consider this done for now?
