### ISSUE TITLE
Can not see spawned 2D mesh in 2D mode without any camera movements before

### ISSUE THREAD

**Issue by rewin123** [rewin123/space_editor#248]
![image](https://github.com/rewin123/space_editor/assets/10954133/4064b2f9-19f4-470a-89bd-4500492ebf5d)

**Comment by naomijub** [comment]
Relates to https://github.com/rewin123/space_editor/pull/228

**Comment by naomijub** [comment]
https://github.com/rewin123/space_editor/pull/252
