### ISSUE TITLE
Add component must be same width as tab (currently same width as srollable content of tab)

### ISSUE THREAD

**Issue by rewin123** [rewin123/space_editor#255]
![image](https://github.com/rewin123/space_editor/assets/10954133/2241c952-fc45-45e4-8931-26fc2108c689)

**Comment by naomijub** [comment]
This is weird, I don't seem to have that bug 🤔

**Comment by rewin123** [comment]
I have a wiiiiiiiiiiiiiiiiiiiiiiiiiide component AnimationPlayer
![image](https://github.com/rewin123/space_editor/assets/10954133/54e8ece7-cd30-482d-84ef-2bda7f53adea)

**Comment by naomijub** [comment]
Well in my window it is the size of the tab. However, I do see why this is happening, as your component is larger than the tab size 😂

**Comment by naomijub** [comment]
Please check if this has been fixed with the last merge

**Comment by rewin123** [comment]
![image](https://github.com/rewin123/space_editor/assets/10954133/b32b3dc9-31a7-4334-a9e6-b9b69948faba)

**Comment by naomijub** [comment]
Which prefab are you using? Will try to fix this again today

**Comment by naomijub** [comment]
![image](https://github.com/rewin123/space_editor/assets/14813660/2a3c91ad-3982-47b1-93f4-07daae3f6745)

![image](https://github.com/rewin123/space_editor/assets/14813660/69c8b28b-7997-4fc8-9c1b-7c480c6443bc)
