### ISSUE TITLE
Use bevy_mod_outline for highlighting selecten entities

### ISSUE THREAD

**Issue by rewin123** [rewin123/space_editor#259]
https://github.com/komadori/bevy_mod_outline

![image](https://github.com/rewin123/space_editor/assets/10954133/44e62262-69cb-463b-aa00-25df4a1f91a0)

Will be more easy for determine selected mesh

Plan:

- [ ] Make select agnostic plugin
- [ ] Create in this repo wireframe selection render
- [ ] Create in another repo mod ourtline based repo (so, we will have less problems with updating to next bevy version)

**Comment by naomijub** [comment]
I like the idea but I am not certain about having another library that we indirectly have to maintain up to date

**Comment by rewin123** [comment]
We can try to create some semblance of it. Sometimes, if there are many triangles, it is almost impossible to see the selected model

**Comment by rewin123** [comment]
![image](https://github.com/rewin123/space_editor/assets/10954133/a6055207-fb55-4f71-83c2-bb4487b2187c)

Fixed at #281
