### ISSUE TITLE
Split editor_ui into editor_ui and editor_tabs

### ISSUE THREAD

**Issue by rewin123** [rewin123/space_editor#267]
Currently, the ui code is over-complicated and different related parts of it are scattered in random places. 
For example tabs logic is in editor_tab.rs lib.rs ui_plugin.rs
For simplification I suggest to put all core logic of dock/tabs systems in a separate crate, independent of any other space_* crate. This will greatly increase both bug finding, testability and flexibility of the editor

- [x] Split crate
- [x] Make tab name not specific. Allow to use any enum for tab name
- [x] Move sizing and colors modules out of editor_tab crate
- [x] Create own plugin for editor_tabs

**Comment by naomijub** [comment]
is this done?

**Comment by rewin123** [comment]
Yep
