### ISSUE TITLE
Add to CI examples and main running

### ISSUE THREAD

**Issue by rewin123** [rewin123/space_editor#270]
Sometimes examples can crash even if program is compiling. We need to test that examples can be executed and they will return 0 exit code

And we need to run this on at least ubuntu and mac machines

**Comment by naomijub** [comment]
https://github.com/bevyengine/bevy/blob/50699ecf76800e5b1b31bd9b6845b30e4ede5e32/.github/workflows/validation-jobs.yml#L69

**Comment by naomijub** [comment]
https://github.com/rewin123/space_editor/pull/287
https://github.com/rewin123/space_editor/pull/286
