### ISSUE TITLE
Undo functionality

### ISSUE THREAD

**Issue by rewin123** [rewin123/space_editor#29]
Its need at least undo for manipulating transforms, adding components, creating entities

- [x] Component change undo
- [x] Test for transform
- [x] Test for all registered in editor components
- [x] Single entity add 
- [x] Single entity remove
- [x] Entity with parent relations remove/add
- [x] Fix bugs

**Comment by naomijub** [comment]
This seems to be hard, any ideas on how to do it?

**Comment by rewin123** [comment]
Half done already in the develop branch. The main idea is to automatically track changed components, label them and after editing is complete, save their state to the world change chain. This chain will allow to move undo/redo manner between saved component states. The main difficulty, though, is recreating multiple objects at once with internal references and parental relationships. I'm still thinking about one of two approaches: keep a full "copy" of the world in an internal cache, or delete objects only through signals so that they can be stored in the world change chain.
