### ISSUE TITLE
Gltf import is wrong when not executing in app directory

### ISSUE THREAD

**Issue by DasLixou** [rewin123/space_editor#297]
**Describe the bug**
```
ERROR bevy_asset::server: Path not found: C:\path\to\project\editor\assets\my_asset.glb
```
The asset is in `C:\path\to\project\assets\my_asset.glb` and it gets selected.. somewhat correct (have to go one folder up and then am somehow in "C:\" but its the correct folder, but when I select it, the path in the error adds the `\editor` directory and fails.

**To Reproduce**
Have a cargo workspace with an `editor` member where the editor is and load a gltf which is not in `.\editor\assets\` but in `.\assets\`

**Expected behavior**
Load the correct file

**Screenshots**
![image](https://github.com/rewin123/space_editor/assets/82600264/86b3731d-4485-432e-8650-7fbb3a4e255d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Project Version: git reference on main branch
 - Rust Verion: 1.77.2

**Comment by naomijub** [comment]
@rewin123 v0.6?

**Comment by naomijub** [comment]
Will try to deal with this until saturaday

**Comment by naomijub** [comment]
do you have an open source repo I could fork to look into this? I was not able to reproduce

**Comment by naomijub** [comment]
So, looking around, we hardcoded the gltf and glb to be at path `assets/models/`.

There is some circular dependencies between the multiple crates to solve that, but I will try to figure it. This should solve your issue

**Comment by rewin123** [comment]
Sorry for long waiting. Will try to fix on this week

**Comment by rewin123** [comment]
I have restored the conditions described in Issue and everything works on main
