### ISSUE TITLE
wgpu Validation Error on startup

### ISSUE THREAD

**Issue by SolarLiner** [rewin123/space_editor#298]
**Describe the bug**
The editor somehow causes Bevy to create an invalid viewport rect, that is outside the render target.

**To Reproduce**
From a blank Bevy project, add the space editor as shown on the README, and add the SpaceEditorPlugin, as well as the `simple_editor_setup` startup system.

**Expected behavior**
Editor opens without causing a wgpu failure.

**Screenshots**
wgpu shows the following failure message (shown here with the DX12 backend, but is also reproducible on the Vulkan backend)

```
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 1, Dx12)>`
    In a set_viewport command
    Viewport has invalid rect Rect { x: 2001.0, y: 74.0, w: 7999.0, h: 9896.0 }; origin and/or size is less than or equal to 0, and/or is not contained in the render target (1600, 900, 1)
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Project Version 0.5 (assuming "project version" here means the version of space editor), rev 5067ab5d18f0bc678feadd2307d356e64cd392e2
 - Rust Verion: 1.77.2

**Additional context**
Removing the `simple_editor_setup` removes the validation error, but leaves the "Game View" tab empty.

This bug seems to be Windows-specific, as I cannot reproduce on macOS.

As is often the case with these kinds of bugs, I have a display scale factor of 125% in my system settings, though the viewport values don't seem to nicely tie to the display value by that display scale factor, so I don't know how relevant this is.

**Comment by naomijub** [comment]
I've seen that error before, will try to take a look this week

**Comment by rewin123** [comment]
I have encountered this bug and for me it disappeared after updating space_editor to 0.13.2. (That is, the bug was tied specifically to 0.13.1). Can you please try this PR #299 ?

**Comment by SolarLiner** [comment]
That unfortunately does not solve the issue, I get the same wgpu validation error.

**Comment by naomijub** [comment]
Is your windows Up to date?

**Comment by SolarLiner** [comment]
I believe it is, I had a system update a few days ago and haven't had any GPU driver update notifications popping up, but I'll check for updates tomorrow and see if anything needs to be done.

**Comment by SolarLiner** [comment]
I have everything up to date, except for my GPU drivers, which I updated before trying again, to no avail, it still fails with the same error.

Here's the full log:

```
2024-04-16T18:07:59.230457Z  INFO bevy_winit::system: Creating new window "App" (0v1)
2024-04-16T18:08:00.193404Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3060", vendor: 4318, device: 9476, device_type: DiscreteGpu, driver: "", driver_info: "", backend: Dx12 }
2024-04-16T18:08:00.624858Z ERROR space_editor_ui::meshless_visualizer: Failed to dynamic load assets. Loading defaults from memory
2024-04-16T18:08:00.635044Z  INFO space_bevy_xpbd_plugin: Add bevy_xpbd_3d plugin to editor
BevyXpbdPlugin::build
2024-04-16T18:08:00.706894Z  INFO space_editor_ui: Set start state
2024-04-16T18:08:00.818532Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Home", kernel: "22631", cpu: "13th Gen Intel(R) Core(TM) i5-13600K", core_count: "14", memory: "31.8 GiB" }
2024-04-16T18:08:00.892620Z  INFO bevy_input::gamepad: Gamepad { id: 0 } Connected
2024-04-16T18:08:01.458089Z ERROR log: Handling wgpu errors as fatal by default    
thread '<unnamed>' panicked at C:\Users\solarliner\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.3\src\backend\wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 1, Dx12)>`
    In a set_viewport command
    Viewport has invalid rect Rect { x: 2001.0, y: 74.0, w: 7999.0, h: 9896.0 }; origin and/or size is less than or equal to 0, and/or is not contained in the render target (1600, 900, 1)
```

**Comment by naomijub** [comment]
Can you try using the branch v0.6? I think my fix for this issue was merged in that branch and I don't recall what it was

**Comment by naomijub** [comment]
So running `cargo run --example space_example` and `cargo run --example space_example --release` on `main` seems to work well on my MacOS and my Windows 🤔, I'm really curious what can it be. 

Do you have space_editor as a plugin and you project bevy has `no-default-features`?

**Comment by SolarLiner** [comment]
edit, it seems that it only fails when I'm using the editor as a plugin in a separate project -- under the same commit, running the examples work, but running as a plugin in a separate empty project fails. I've tried matching the bevy versions (was using 0.13.2 before, and moved it to 0.13.1) to no avail.

**Comment by naomijub** [comment]
That is odd. We have a test for that, but it is using Linux as windows takes longer to compile. Will try to fix it

**Comment by naomijub** [comment]
it seems to be working in linux https://github.com/rewin123/space_editor/actions/runs/8731039708/artifacts/1424227195

**Comment by naomijub** [comment]
Added a windows example to the CI, let's see if I can reproduce the error

**Comment by naomijub** [comment]
seems to be working fine https://github.com/rewin123/space_editor/actions/runs/8742952685/job/23992381723:


![screenshot-100](https://github.com/rewin123/space_editor/assets/14813660/e814f357-be77-4536-b577-e5676ae953bc)

**Comment by SolarLiner** [comment]
That job seems to be running an example, which also runs fine on my Windows machine. It's when I use it in a separate project, added as a dependency, that it fails.

This is making me think that there is probably some conflict in the dependency resolution by cargo then.

**Comment by LgnMs** [comment]
When I use the `RigidBody` from the `bevy_rapier3d` library, I encounter an error. @SolarLiner @naomijub 

```rust
commands
        .spawn((
            RigidBody::KinematicPositionBased,
            SceneBundle {
                scene: asset_server.load("Player.gltf#Scene0"),
                transform: Transform::from_xyz(0.0, 0.5, 0.0),
                ..default()
            },
            Speed(5.0),
            Player,
            Name::new("player"),
        ))
```

**Comment by rewin123** [comment]
> The project is consuming bevy and space editor as external dependencies in the test. However, it is a member of the workspace for enabling rust analyzer. I tried using it as an external dependency in another project in my windows machine and was not able to reproduce it.
> 
> I won't have my windows machine for the next month, so this is my limit helping with this issue. @rewin123

Sorry for late reply. Will try reptoduce bug today

**Comment by rewin123** [comment]
> When I use the `RigidBody` from the `bevy_rapier3d` library, I encounter an error. @SolarLiner @naomijub
> 
> ```rust
> commands
>         .spawn((
>             RigidBody::KinematicPositionBased,
>             SceneBundle {
>                 scene: asset_server.load("Player.gltf#Scene0"),
>                 transform: Transform::from_xyz(0.0, 0.5, 0.0),
>                 ..default()
>             },
>             Speed(5.0),
>             Player,
>             Name::new("player"),
>         ))
> ```
I'll try to watch it today too. Do you have the same error as the author of the issue?

**Comment by rewin123** [comment]
> > The project is consuming bevy and space editor as external dependencies in the test. However, it is a member of the workspace for enabling rust analyzer. I tried using it as an external dependency in another project in my windows machine and was not able to reproduce it.
> > I won't have my windows machine for the next month, so this is my limit helping with this issue. @rewin123
> 
> Sorry for late reply. Will try reptoduce bug today

Was able to reproduce. Indeed, at 100% screen resolution everything works, but at 125% it crashes. Starting to fix it

**Comment by LgnMs** [comment]
> > When I use the `RigidBody` from the `bevy_rapier3d` library, I encounter an error. @SolarLiner @naomijub
> > ```rust
> > commands
> >         .spawn((
> >             RigidBody::KinematicPositionBased,
> >             SceneBundle {
> >                 scene: asset_server.load("Player.gltf#Scene0"),
> >                 transform: Transform::from_xyz(0.0, 0.5, 0.0),
> >                 ..default()
> >             },
> >             Speed(5.0),
> >             Player,
> >             Name::new("player"),
> >         ))
> > ```
> 
> I'll try to watch it today too. Do you have the same error as the author of the issue?

When I ran the [example,](https://github.com/rewin123/space_editor/blob/main/examples/space_example.rs) everything was fine, but when I added it to my personal demo, this error occurred.

**Comment by naomijub** [comment]
Hey guys, sorry I haven't been responding. I am in process of moving to another state and haven't had time to touch the project. Mid may I should be able to get back and help more

**Comment by rewin123** [comment]
I really apologize for the late fix. #304  fixed a bug on windows machine on my machine with 125% screen size

**Comment by naomijub** [comment]
@SolarLiner the bug should have been fixed in main

**Comment by SolarLiner** [comment]
I can confirm it works now on the main branch!

**Comment by rewin123** [comment]
Thanks for double-checking!
