### ISSUE TITLE
Translation added each frame to subscene when inside the editor

### ISSUE THREAD

**Issue by PiergiorgioZagaria** [rewin123/space_editor#305]
**Describe the bug**
When importing a subscene, like for example a platform with a rigidbody, when modifying either the position or rotation, the subscene keeps moving by that transform when inside the editor, but stops when running the game

**To Reproduce**

https://github.com/rewin123/space_editor/assets/75474806/e6e555e6-f596-4429-b8a8-eaf70f73b6d1

Compiled with the following code:
```rust
use bevy::prelude::*;
use space_editor::prelude::*;

fn main() {
    App::default()
        .add_plugins((DefaultPlugins, SpaceEditorPlugin))
        .add_systems(Startup, simple_editor_setup)
        .run();
}
```

And the following dependencies:
```toml
[dependencies]
space_editor = { git = "https://github.com/rewin123/space_editor.git" }

[dependencies.bevy]
version = "0.13"
default-features = false
features = [
  "multi-threaded", # Run with multithreading
  "bevy_asset",     # Assets management
  "bevy_scene", # Scenes management
  "bevy_pbr",  # 3D (physically-based) rendering
  "bevy_gltf", # GLTF 3D assets format support
  "ktx2",      # Preferred format for GPU textures
  "zstd",      # ZSTD compression support in KTX2 files
  "asset_processor", # Asset processing
  "file_watcher",    # Asset hot-reloading
  "wayland",         # (Linux) Support Wayland windowing system
  "dynamic_linking",  # Dynamic linking for faster compile-times
  "embedded_watcher", # Hot-reloading for Bevy's internal/builtin assets
]
```

**Expected behavior**
Setting the transform of the subscene shouldn't mae it move in the editor

**Screenshots**
I uploaded the video as an example

**Desktop (please complete the following information):**
- Fedora 40
- rust version: v1.80.0-nightly

**Comment by naomijub** [comment]
We are a bit stalled this couple of months, and we'll take a look as soon as we have time.

**Comment by rewin123** [comment]
I have time to fix the bugs in main for now. I already tried to replicate the bug on a simple cube model, but everything worked correctly for me. Perhaps the problem is that I didn't cover some kind of data in your model when converting it to bevy scene. Would you feel comfortable sharing the 3d model from the video?

**Comment by PiergiorgioZagaria** [comment]
[assets.tar.gz](https://github.com/rewin123/space_editor/files/15287372/assets.tar.gz)

Here it is. It's not mine, it comes from [this github project](https://github.com/KenneyNL/Starter-Kit-FPS) (kenney.nl FPS starter kit for godot). Wanted to try and rewrite it in bevy

**Comment by rewin123** [comment]
I was able to reproduce! I didn't immediately notice that you were using the "Open subscene" button. Canonically in space_editor you need to use the leftmost button in the top panel to reopen saved editor scenes. It exactly opens the prefab.

![image](https://github.com/rewin123/space_editor/assets/10954133/462eb0a1-0b1d-41a0-8a60-2a771a5f14f1)

**Comment by rewin123** [comment]
"Open subscene" is designed to open gltf with skeletal animation and perceives the opened object as a model, which has a center of coordinates zero. But the bug with infinite rotation is certainly a bug and I will try to fix it.

**Comment by PiergiorgioZagaria** [comment]
How do you add a prefab to another scene then? That's what I wanted to do.

Like for example, I add the rigidbody and collider to the platform, make it a scene, and then import it a bunch of times in the main_game scene. This way I don't have to set the collider all the time I create a new platform.

Do I need to spawn it from code?

**Comment by rewin123** [comment]
There are three paths we have in version 0.5. 

1. From the code
```rust
commands
        .spawn(PrefabBundle::new("scenes/Scene0.scn.ron"))
        .insert(Name::new("Prefab"));
```
2. We can add a PrefabLoader component to the entity and specify a specific path
![image](https://github.com/rewin123/space_editor/assets/10954133/6980f340-db14-4b78-892f-2f39411ad089)
3. Open subscene is also the way to solve this problem, after I fix the bug. But we have a number of improvements to these mechanics specifically in v0.6

**Comment by rewin123** [comment]
Alternatively, you can use "Clone" for entities. For example, if you set the path once for a subprefab or colliders, you can easily reproduce it. It allows you to clone an entity and all its children and all its components. It is available either through the context menu in the Hierarchy panel or by holding Alt and pulling the gizmo in the entity move mode. You can even clone multiple entities with Alt+Shift

**Comment by rewin123** [comment]
I figured out the cause of the problem. bevy_xpbd glitches if rigidbody has some parent and starts to continuously shift/rotate by the parent's transform value. As far as I remember everything worked in the old version of bevy_xpbd and this is some new changes or I don't remember well, but in any case I need to create a mechanism to load prefabs without creating additional parents. It is not difficult and it will take me hopefully only two days. I'll add it to the 0.6 branch and post here when I'm done and check that there are no more problems with the new mechanism for rigidbody.

**Comment by rewin123** [comment]
@PiergiorgioZagaria 
Looks working for me #306

**Comment by PiergiorgioZagaria** [comment]
Works for me too, just tested the branch :+1:  . Do I close the issue or wait until it's merged?

**Comment by rewin123** [comment]
I will merge ang close. Thanks for bug report and help!
