### ISSUE TITLE
Camera Transform Issues

### ISSUE THREAD

**Issue by MiniMinerX** [rewin123/space_editor#314]
When making an entity with Camera3d a child of another entity, the camera transform is not updated properly. 

This is due to camera_view.rs, around line 300 in the line:

mut cameras: Query<(&mut Camera, &mut Transform), Without<EditorCameraMarker>>,

By only taking the Transform and not the global transform, the real_cam_transform is not adjusted to the true global positon of the camera.

I propose replacing the line with:

mut cameras: Query<(&mut Camera, &mut GlobalTransform), Without<EditorCameraMarker>>,

This allowed any of my cameras that were children to update the viewport properly.

**Comment by rewin123** [comment]
Thank you for the issue and the suggestion! I'll try this tomorrow

**Comment by rewin123** [comment]
Fixed and tested for child camera. Real camera transform updating correctly right now. But I gound that gizmo transform works badly with child entities. Will fix in another issue
