### ISSUE TITLE
File Structure reorganization

### ISSUE THREAD

**Issue by naomijub** [rewin123/space_editor#62]
The current file structure makes it harder to export the prefab plugin as a crate, a new file strucutre was proposed at https://github.com/rewin123/space_editor/pull/61 : 

**src/** _<- has editor executable_
**crates/**
- prefab _<- external crate that can be published to crates.io_
- editor _<- everything related to editor_
- shared _<- things shared between prefab and editor_

**modules/** _<- the community modules to be featured in the editor (it could be inside crates, but I think it could cause confusion to live with crates._
- xpbd
- rapier
- vx_bevy
- openxr
- etc etc

The shared library seems to be a discussion point.

The advantage of the new structure is that we can use workspaces and enable a better decoupling of the code, while third party crates or community modules being separated from the core project.

**Comment by naomijub** [comment]
Do you want help on this one?

**Comment by rewin123** [comment]
Not before I upload Undo pull request (probably in this day i will).

We can discuss the new structure for now. For now, I still see a structure without a shared folder, so that the prefab folder is fully inlined into the editor crate (i.e. all the contents of the shared will essentially be inside the prefab folder).

**Comment by rewin123** [comment]
@naomijub I finally finished Undo logic. (1100 lines of code T_T) And opened a pull request to reorganize the code structure. May  I ask you to help me with these questions:
1. Do EditorState::Game or EditorState::Editor need to be inside prefab crate? It seems to me unnecessary and these states should only appear when adding an editor plugin
2. I found a use for the shared folder. There you can put the registration of components for the editor, which should change its behavior depending on whether the editor plugin is plugged in or just the prefab plugin is plugged in.
3. Some pieces of the editor can be broken into smaller crates, such as enitity cloning mechanics, persistance, undo logic. Is it reasonable to do this?

**Comment by naomijub** [comment]
Give me some time to review everything and give suggestions. If needed I plan to make a PR directly into file reorg branch. OK?

**Comment by rewin123** [comment]
Yeah, sure!
