### ISSUE TITLE
Adding new tabs split the tab space instead of adding a new tab

### ISSUE THREAD

**Issue by naomijub** [rewin123/space_editor#65]
![image](https://github.com/rewin123/space_editor/assets/14813660/8c05fa42-51d8-4e94-9393-038282d944f4)

**Comment by rewin123** [comment]
I want to add a field in Settings that will allow selecting the behavior of opening a tab. Of course, the behavior selection will be automatically saved between launches.

**Comment by naomijub** [comment]
Sounds doable, this week I'll have a pairing session with a friend and I think this will interest her
