### ISSUE TITLE
Components Order

### ISSUE THREAD

**Issue by naomijub** [rewin123/space_editor#68]
What do you think of standardizing a components order?

I feel it is better to Have Components Name and Transform as top components for every entity. Currently they are kind of random.

Nicely, you show the entity name as a heading in the inspector, but I guess transform is very important as well

**Comment by rewin123** [comment]
Currently, if nothing is broken, the components are displayed in alphabetical order. But yes. It's possible to introduce prioritization of components display. 

Like

```rust
// default is zero, lowest
app.editor_set_show_priority::<Transform>(1);
app.editor_set_show_priority::<Name>(2);
```

**Comment by naomijub** [comment]
Do you like that idea?

**Comment by rewin123** [comment]
Yeah, that's a cool idea
