### ISSUE TITLE
Hierarchy name

### ISSUE THREAD

**Issue by naomijub** [rewin123/space_editor#75]
Hey, what do you think about changing the Entity naming in Hierarchy DrawEntity from:
```rs
fn draw_entity(
// ...

    let entity_name = name.map_or_else(
        || format!("Entity {:?}", entity),
        |name| format!("Entity {}: [{:?}]", entity, name.as_str()),
    );
```

to something like:
```rs
    name.map_or_else(|| format!("Entity {:?}", entity), |name| format!("{} [{:?}]", name.as_str(), entity));
```

then we would have entity names in Hierarchy like: `MyEntityName [0v0], `Cube [0v1]`

**Comment by rewin123** [comment]
This format is more short and readable. So it is better

**Comment by naomijub** [comment]
![image](https://github.com/rewin123/space_editor/assets/14813660/ddb1a4c6-3f48-4d14-bfb6-978c85acb3f7)

Looks like this

**Comment by rewin123** [comment]
Yep. [] is important, i think:)

**Comment by naomijub** [comment]
Which one do you prefer?
![image](https://github.com/rewin123/space_editor/assets/14813660/9f2c8369-fd4d-4b45-906c-9b27e26f2fb9)

![image](https://github.com/rewin123/space_editor/assets/14813660/c50619bf-e58a-4fb8-87b8-1ff872f2c2c6)

Now looking, I think `(0v0)` looks better

**Comment by rewin123** [comment]
Maybe perfect solution is using Grid. Where first column is name, second column is entity. But it is very more cleaner that was

**Comment by rewin123** [comment]
Uh-oh. Or not the grid, it would destroy the logic of the button's click logic:/

**Comment by naomijub** [comment]
> Oh. Or not the grid, it would destroy the logic of the button's click logic:/

true, So until we get a better solution, https://github.com/rewin123/space_editor/pull/76
