### ISSUE TITLE
Sometimes camera viewport updates incorrectly if change game view tab size

### ISSUE THREAD

**Issue by rewin123** [rewin123/space_editor#80]
![image](https://github.com/rewin123/space_editor/assets/10954133/709463d1-c26b-4a5c-b460-7c1330f02dc2)

**Comment by naomijub** [comment]
I think this happens because of the way we are setting the viewport in game view. I have encountered that issue trying to get a mini camera in the game view

**Comment by rewin123** [comment]
It's a bit strange that this worked correctly in bevy 0.11😅

**Comment by naomijub** [comment]
Little surface changes and lots of under the hood changes
